web_search = "live"

approval_policy = "never"
sandbox_mode = "workspace-write"
allow_login_shell = false

[sandbox_workspace_write]
network_access = false
writable_roots = ["/home/orito/ghq/github.com/MatchaChoco010/toy-path-tracing", "/tmp"]

[features]
shell_snapshot = true

[mcp_servers.markitdown]
command = "docker"
args = ["run", "--rm", "-i", "markitdown-mcp:latest"]
